services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3Headless\Typo3Ai\:
    resource: '../Classes/*'

  TYPO3Headless\Typo3Ai\EventListener\AddTranslateButton:
    public: true
    tags:
      - name: event.listener
        identifier: 'typo3headless-typo3ai/eventlistener/add-translate-button'
